### ISSUE TITLE
problem on windows 10

### ISSUE THREAD

**Issue by dgiunchi** [ua-i2cat/gst-unity-bridge#12]
I've just downloaded the project and follow the instructions for setting up. I've GStream 1.8.2. When the scene starts, the texture doesn't refresh, but the audio is present. I use Windows 10 and Unity 5.3.5f1

**Comment by segfaultxavi** [comment]
Can you attach the debug output?

##

**Comment by dgiunchi** [comment]
I checked on the editor, only in the editor is missing, after build it's all ok. Sorry for that, you can close the Issue.
